### ISSUE TITLE
!greroll unexpected behavior

### ISSUE THREAD

**Issue by crozynski** [jagrosh/GiveawayBot#116]
I run a regular giveaway that announces 5 winners.
Often a winner has left the discord or wants to drop out of the giveaway.
When I reroll it only announces 1 winner, and it includes the existing winners from the pool.
I think !greroll could be improved if the command prompted options to:
– Include existing winners in reroll? Y/N
– Reroll 1 new winner or all winners? Y/N

**Comment by JetCrooked** [comment]
for the first part, I don't think that would be possible due to the bot's database only tracking ongoing giveaways, not past ones; however a workaround that would work for this is you can remove winners' reactions to the giveaway they won before rerolling it, so they can't be picked again.
as for the second, this seems like a simple enough addition to the reroll command that shouldn't be too hard to add so hopefully it can be added!

**Comment by janangeloaguilar4-source** [comment]
Pls fruit, I'm really poor. I need some fruit that can support my grind, and improve my pvp. User HenzoZxv2

**Comment by leomardesquibol12-create** [comment]
**** can I have a new rod pls

**Comment by dingdong59** [comment]
can I have a trident

**Comment by dingdong59** [comment]
or 300 gems
username: RonaldotheGOAT

**Comment by emperorvergara5-ship-it** [comment]
Pls give me some bro

**Comment by gonzagajemma8-sys** [comment]
guys can you donate me any amount of robox my user is malupiton111115
