### ISSUE TITLE
Being able to opt out of a giveaway

### ISSUE THREAD

**Issue by martinbndr** [jagrosh/GiveawayBot#149]
Hello,
currently the beta bot sends a ephemeral message saying that the user already entered the giveaway:
![image](https://user-images.githubusercontent.com/55140357/162052925-c419a904-c5a6-4c39-a666-8eddb3380662.png)

In some situations it can be useful to opt out of it again. 
Some servers ping lots of people after starting a giveaway, then people react / press any button fast. And then they read whats it about. ( Not all but some )
Then they realize they dont want to enter or they do not meet a certain giveaway requirement.

Maybe you could make another Button **inside** the ephemeral message. If that button is pressed the user can remove from the giveaway.
Sry if this already has been suggested/or is already part of the development plan.

Have a nice day!

**Comment by RJloveMC** [comment]
Leaving the giveaway doesn't update the entrant number

**Comment by jagrosh** [comment]
> Leaving the giveaway doesn't update the entrant number

This is known and functioning as intended given the current state of how ratelimiting works. Since the button to leave the giveaway isn't on the giveaway message itself, the response to the request to leave can't directly affect the original giveaway message. Whenever someone enters the giveaway it will update to the correct number.
