### ISSUE TITLE
Is there a way to get @ replies and or # to work in the description area?

### ISSUE THREAD

**Issue by bburzycki** [jagrosh/GiveawayBot#191]
Is there a way to get @ replies and or # to work in the description area of the giveaway post. 

Also is there a fully updated list of all slash commands. I am not sure the bot site is updated? Or is it?

**Comment by n-11-eleven** [comment]
**NOTE: The Githuh repository is for feature requests, or otherwise for reporting bugs. In case you have further support inquires like this one, contact the support channel.**

The description you provide is put into the "description" field of an embed, where you can insert user/role mentions, and channel mentions too.
FORMAT FOR:
(1) user mentions is: `<@X>` where X is the USER ID;
(2) role mentions is: `<@&Y>` where Y is the ROLE ID;
(3) channel mentions is: `<#Z>` where Z is the CHANNEL ID.

As for your second question, the website has a list of all commands, and its updated too. Besides, you can run `/ghelp` and it'll show you a list of commands, too.

**Comment by bburzycki** [comment]
Ok thanks - Thought we had to come here for feature requests, just had no idea this was already in there. Also I beleive I read a post about an updated list of slash commands coming, I will go with what is on the site and in help as the latest and greatest - thanks
