### ISSUE TITLE
Why can't I add a bot to any server?

### ISSUE THREAD

**Issue by sPatrickO** [jagrosh/GiveawayBot#275]
![image](https://github.com/user-attachments/assets/9415c8f5-d5f4-4cc2-a19e-28d5957b2d2c)

**Comment by bup0441** [comment]
Discord has unverified GiveawayBot and GiveawayBot Beta due to a change in how bot verification works, requiring a developer's ID to be resubmitted once every three years. GiveawayBot's developer previously used an alternate form of verification that apparently no longer exists; until this is resolved, the bots will not be able to be added to any servers. We do not have an ETA for the bots being re-verified.

**Comment by sPatrickO** [comment]
It's sad
