### ISSUE TITLE
Add the ability to reattach a giveaway to the bot

### ISSUE THREAD

**Issue by brimmasch** [jagrosh/GiveawayBot#280]
If you create a giveaway, then remove/alter the permissions from the bot, let the giveaway hit the time it was supposed to end, and then re-add the permissions, the giveaway is left in a state where the bot will not recognize it with /glist or end it with /gend.  The giveaway will sit indefinitely without ending.

since the giveaway id appears to be the message id, would it not be possible to readd a giveaway to the bot using the message id as the giveaway id?  and then if the bot sees that it should have ended, simply end it.  this way, users can recover from giveaways that should have ended and reroll them if desired.

**Comment by jagrosh** [comment]
When a giveaway ends, it is permanently deleted. This happens regardless of if the final winning message succeeded, so no, there is no way to look it up once it ends.

**Comment by brimmasch** [comment]
why does it need to look it up?  it requires the read message history permission so it should be able to see that it created the message and that it has a format of a giveaway.  why couldn't it be written to notice that this message is a giveaway that was never closed when it was supposed to (in a bad state) and then modify/finish/edit the message and finish it?  or are you saying that somewhere, even with the message id, there is no history of some part of the giveaway metadata required for this?  like the people that joined?  wouldn't it be able to derive those from reactions on the message?  what would the bot need that it wouldn't be able to derive from the message?  wouldn't it be able to parse everything?  everything that it needs to create a message is there and it seems there should be an api to get people who reacted.

**Comment by jagrosh** [comment]
There are no reactions on the message; the button on the message sends a request to GiveawayBot's server where it stores the entries. The list of entries (along with the rest of the giveaway information) is deleted when the giveaway ends.

**Comment by brimmasch** [comment]
> There are no reactions on the message; the button on the message sends a request to GiveawayBot's server where it stores the entries. The list of entries (along with the rest of the giveaway information) is deleted when the giveaway ends.

ah, okay.  and i suppose there is no where in discord's api that keeps button presses?

**Comment by jagrosh** [comment]
Discord does not keep track of button press history, no.

Reactions were used in the past, but the reaction system is extremely unreliable; after certain numbers, Discord simply silently ignores additions, and can entirely fail to respond to attempts to load the reaction list.

**Comment by brimmasch** [comment]
> Reactions were used in the past, but the reaction system is extremely unreliable; after certain numbers, Discord simply silently ignores additions, and can entirely fail to respond to attempts to load the reaction list.

this part i knew and that makes sense.  the rest makes sense.  

thank you for discussing it with me.

**Comment by brimmasch** [comment]
i guess i have one more question.  rather than delete the giveaway as soon as the time expires, it might be possible to hold the deletion until a successful api call to modify the giveaway message is made?

**Comment by jagrosh** [comment]
Saving that kind of data long-term would mean more data that needs to be preserved on the bot's end, plus additional implementations for cleaning up old data, support ending outdated giveaways (that could have extremely outdated user info), and might not even play nicely with Discord's ToS because it could fall out of the period of "needing to store that data." Basically, it's several additional factors for something that I (believe) is a very small problem.  

I don't have specific metrics, but a between-creation-and-end permissions issue is likely a very small subset of reasons a giveaway may fail, and there are many others that would not leave behind any message or means to 'fix' a giveaway. For example: the channel being deleted, the server being deleted, the giveaway message being deleted, giveawaybot being removed from the server, or the channel being intentionally locked/archived.

I'm not explicitly saying that this would never get added, but that it's highly unlikely due to a combination of having many factors to think about/implement for what I suspect is an uncommon problem.
