### ISSUE TITLE
Ability to target a specific channel using gstart

### ISSUE THREAD

**Issue by hypexr** [jagrosh/GiveawayBot#54]
Currently using `!gcreate` to start giveaways in channels other than where the command is issued, but would be nice to be able to use `!gstart`.

**Comment by jagrosh** [comment]
This probably won't be added to `!gstart`, but will likely be one of the parameters once we switch to slash commands

**Comment by jagrosh** [comment]
I've since decided not to include this functionality in the rewrite. 
- The new(ish) Integrations page allows very fine control of which commands can be used where, and in conjunction with channel permissions should allow better control of where giveaways can be held.
- The responses to commands (other than the giveaway itself) are now ephemeral (only visible to the person running the command) so there's no need to worry about extraneous text in the giveaway channel
- Bots are provided with their own permissions in the channel that a slash command is executed, but no other channels, so it's difficult to determine preemptively if a giveaway can be help in any channel other than the channel with the slash command.
