### ISSUE TITLE
Giveawaybot not working

### ISSUE THREAD

**Issue by MysticRavager** [jagrosh/GiveawayBot#69]
for some reason the giveawaybot is not responding to my commands. it shows it offline. why is this? i tried reinviting and still nothing
https://discord.gg/vpm6ZHdNc3
this is my server. feel free to join but please be sure to open a ticket so we know your an admin and supply proper information so we know you are who you say you are for it so we can properly add you to server settings to try to fix the issue

**Comment by lordbinchicken** [comment]
We had an outage affecting Cluster 0 of the bot, first brought to our direct attention around 5:00pm Pacific Standard Time, jagrosh restarted it around 5:20pm and it appeared to return to near complete function within ten minutes.
 - If the bot still appears offline in your server I suggest kicking it and reinviting from https://giveawaybot.party/invite in order to reconnect it to its shardset.
 - If the bot is online in your server but does not respond, make sure that the bot has proper permissions to create giveaways; Read Messages, Send Messages, Embed Links, Add Reactions, Use External Emojis, and Read Message History. Otherwise you can reinvite from the administrator invite at https://giveawaybot.party/alt-invite.
 > If on the off chance that not only is the bot still offline but all the measures I have said fail, my DMs are open, username bup#0441.

**Comment by Sanduhr32** [comment]
_nice_
